# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('female', '女'), ('man', '男')], default='man', max_length=20, verbose_name='状态')),
            ],
        ),
    ]
