# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='名')),
                ('last_name', models.CharField(max_length=32, verbose_name='姓')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('publisher_date', models.DateField(auto_now_add=True, verbose_name='出版日期')),
                ('publisher_state', models.CharField(choices=[('checkout', '已出版'), ('dai', '待出版'), ('status', '审核中')], default='checkout', max_length=20, verbose_name='状态')),
                ('authors', models.ManyToManyField(to='books.Author', verbose_name='作者')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('address', models.CharField(max_length=64, unique=True, verbose_name='地址')),
                ('city', models.CharField(max_length=32, verbose_name='城市')),
                ('state_province', models.CharField(max_length=32, verbose_name='省份')),
                ('country', models.CharField(max_length=32, verbose_name='国家')),
                ('website', models.URLField(verbose_name='网址')),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Publisher', verbose_name='出版社'),
        ),
    ]
